% Add to the path osnap mooring functions:
% pathlocal = pwd; pathosnap = definelocalpath(pathlocal) ;
pathosnap = pwd;
eval(['cd exec' filesep 'dy078'])
run('startup.m');

disp('')
% disp('Did you check that you have the mooring processing functions (RODB + RAPID functions) in your path?')
% disp('If no, you can clone the git repository or download the matlab toolbox from here: https://bitbucket.org/Lhoupert/mooring_processing_toolbox/src')
% disp(' Then just add the toolbox to your matlab path by doing: ')
% disp('addpath(genpath(*path of the toolbox*))')
disp('')
% Add to the path loic's toolbox:
p=path;
%pathmfct = [pathosnap '/../matlab_library_loic'];
%p2 = [...
%     [pathmfct ':'], ...   
%     [pathmfct '/seawater:'], ...      
%     [pathmfct '/cbrewer/cbrewer:'], ...
%     [pathmfct '/m_map:'], ...
%     [pathmfct '/mexcdf/snctools:'], ...   
%     [pathmfct '/mexcdf/mexnc:'], ... 
%     [pathmfct '/mexcdf/netcdf_toolbox/netcdf:'], ...     
%     [pathmfct '/mexcdf/netcdf_toolbox/netcdf/ncutility:'], ...         
%     [pathmfct '/graphic:'], ...           
%     [pathmfct '/dqmc:'], ...      
%     [pathmfct '/gsw_matlab_v3_05_1:'], ...  
%     [pathmfct '/gsw_matlab_v3_05_1/html:'], ...      
%     [pathmfct '/gsw_matlab_v3_05_1/library:'], ...           
%     [pathmfct '/gsw_matlab_v3_05_1/pdf:'], ...        
%     [pathmfct '/gsw_matlab_v3_05_1/thermodynamics_from_t:'], ...
%     [pathmfct '/netcdf:'], ...         
%     ];
% addpath(p2)


