% Save raw ascii data from Seabird SBE26 'Seagauge' to rdb format
%
% Kanzow, 16.04.05
% jym 22 April 2005: Start with clean slate
% EFW 2011 Apr 13
% SKYE 2012 Feb 
% DR - May 2014 - fixed bug with toffset where if found an offset for the
% first instrument on a mooring the same offset would get carried over to
% the second instrument too if no seperate value was present for that one.

close all
global MOORPROC_G
clearvars -except MOORPROC_G

% input - likely to be changed
moor = input('mooring deployment (e.g. ebh2_15_2022) to process:   ','s');

% DY053 NOTE : It is much better to manually delete on-deck records
% manually in the raw data file
cutoff1 = 1;   % Number of time steps (30 min) to cut off the record at the start for a nice graph
cutoff2 = 1;   % Number of time steps (30 min) to cut off the record at the end for a nice graph

% The path of the offsetfile is still preliminary
%  --> there are two offset files used for d324, the one below by this
%      program and seagauge/bpr_clock_offset.dat by
%      seagauge_processing_002.m  (zszuts)

pd = moor_inoutpaths('bpr',moor);

% There are 2 clock offset files for BPR instruments:
% clock_offset.dat (in raw/oc459/) and BPR_clock_offset.dat in
% (raw/oc459/seagauge/):
% - clock_offset.dat corrects for constant day/year offsets that
% arise from incorrect instrument setup at the beginning of the
% record.
% - bpr_clock_offset.dat corrects for smaller offsets measured upon
% recovery in stage2 processing, and are applied as linear trends
% for the whole record.

% the wrap_correction coefficients are found in the .hex files generated by
% the SBE software
wrapped_sensor = [388   389  390   391   394   395   396   397   414  399 400];
wrap_correction= [47.7  47.7 47.7  47.7  47.7  79.4  79.4  79.4  47.7  79.4 79.4];

sg_code        = 465; % code for seagauge
%toffset        = 0;  % time offset

[lat,lon,wd,sdate,stime,edate,etime,z,type,serial]= ...
    rodbload(pd.infofile,...
    'Latitude:Longitude:WaterDepth:StartDate:StartTime:EndDate:EndTime:z:instrument:serialnumber');


% ----------------------------------------

sgI          = find(type==sg_code);
sn           = serial(sgI);

% NB The seagauge dir in outpath must be created first
if ~exist(pd.stage1path,'dir')
    warning('creating directory %s',pd.stage1path)
    mkdir(pd.stage1path)
end

disp(pd.stage1log);
log           = fopen(pd.stage1log,'w');
fprintf(log,'Processing of SBE26s  from mooring %s \n Date: %s \n',moor,datestr(clock)');
fprintf(log,'Operator: %s\n',MOORPROC_G.operator');


for ins = 1 : length(sgI)
    
    serialnumber = sn(ins);
    instrdepth   = z(sgI(ins));
    
    outfile      = fullfile(pd.stage1path,sprintf(pd.stage1form,serialnumber));    
    % ------ data input file and log file    
    infile = dir(fullfile(pd.rawpath,sprintf('%4.4d*.tid',serialnumber)));
    if isscalar(infile)
        infile = fullfile(infile.folder,infile.name);
    else
        warning('no file or more than one file for seagauge %d',serialnumber)
        keyboard
    end
    %disp(['SBE-26 instrument ',num2str(serialnumber),' has been found'])
    
    fprintf(log,'Serial number: %4.4d\n',serialnumber);
    fprintf(log,'Target Depth [m]: %4.4d\n',instrdepth);
    fprintf(log,'Input file: %s\n',infile);
    fprintf(log,'Output file: %s\n',outfile);
    
    
    % load data and carry out basic checks
    
    [P,T,C,S,jd,meas,sampling_rate,qflag] = load_seagauge(infile,log);
    
    % ----------------------------------------------------------------
    % -------check data ----------------
    % ----------------------------------------------------------------
    
    
    % ---- check for potential time offset entry in the 'offsetfile' -----
    
    % reset toffset to zero so don't carry over from previous iteration of
    % loop
    toffset=0;
    fidoff = fopen(pd.offsetfile,'r');
    
    if fidoff<0
        
        %fprintf(fidlog,['Time offset file NOT found, \n NO check for ',...
        %    'potential offset in recorded time applied \n'],offsetfile)
        fprintf(1,['Time offset file  NOT found, \n NO check for ',...
            'potential offset in recorded time applied \n'],pd.offsetfile)
    else
        
        while 1
            zeile = fgetl(fidoff);
            
            if ~ischar(zeile)
                break
            end
            
            if ~isempty(findstr(zeile,moor))
                val = findstr(zeile,' ');
                val = str2num(zeile(val:end));
                
                if val(1) == sg_code && val(2) == serialnumber
                    toffset = val(3) + val(4)/24  ;
                    fprintf(1,['Instrument has time offset of %8.4f days ',...
                        '(rel. GMT) \n'],toffset);
                    fprintf(log,['Instrument has time offset of %8.4f days',...
                        ' (rel. GMT) \n'],toffset);
                    break
                end
            end
        end   % while
        
    end  % fidlog
    
    jd = jd - toffset; %apply potential correction of recorded time
    
    bottomstart     = julian([sdate(:)' hms2h([ stime(:)' 0])]);
    bottomstop      = julian([edate(:)' hms2h([ etime(:)' 0])]);
    
    if jd(end) < bottomstop
        fprintf(1,'\n\n W A R N I N G: Record already ends before end of mooring deployment period: \n Recorded time could be wrong!! \n')
    end
    if jd(1) > bottomstart
        fprintf(1,'\n\n W A R N I N G: Record only starts after beginning of mooring deployment period: \n Recorded time could be wrong!! \n')
    end
    
    
    % --- check if data if wrapped ----------------------------------------
    
    wrap =  find(serialnumber == wrapped_sensor);
    figure(99);clf
    plot(P)
    grid on
    title(['Serial number: ',num2str(serialnumber),'; target depth:',num2str(instrdepth)])
    hold on
    disp(['The bottom pressure may contain "wrapped" data - inspect figure 99'])
    corr= input(['Do you want to correct for "wrapped" data? y/n '],'s');
    
    %%  if ~isempty(wrap)&
    if strcmp(corr,'y')
        if ~isempty(wrap)
            offset = 2^19 / wrap_correction(wrap)/1.4503774;
        else
            wrap_correction = input(['Insert pressure coefficient M from the ',...
                'hex data file of sensor #',num2str(serialnumber),': ']);
            offset = 2^19 / wrap_correction/1.4503774;
        end
        
        ind = input(['From figure 99 select index range of wrapped',...
            ' data [ind1 ind2]: ']);
        Pneu = P;
        Pneu(ind(1):ind(end)) = Pneu(ind(1):ind(end)) + offset;
        % jym 22 April 2005: Change plottin slightly to ensure both curves are
        % easily visible
        clf,
        plot(Pneu,'r')
        hold on
        plot(P,'b')
        grid on
        legend('P_{wrapped}','P_{corrected}');
        success = input('Was correction successful? y/n ','s');
        
        if strcmp(success,'n')
            disp('Break')
            break
        else
            P = Pneu;
            fprintf(log,[['Correction for "wrapped" data applied for elements'], ...
                [' : [%d - %d] \n']],ind);
        end
        close(99)
    end
    
    %% end
    
    % ----- plot ---------------
    
    plotstart = julian([2015 6 1]); % start of plots
    jd_start = julian([sdate(:)' hms2h([stime(:)' 0])]);
    jd_end   = julian([edate(:)' hms2h([etime(:)' 0])]);
    
    ii = find(jd<jd_end & jd>jd_start+.3);
    figure(1)
    clf
    % DY053 sa02sc : added linkaxes for scaled zooming of plots and grid on
    [p1]=subplot(2,1,1);hold on ;grid on;
%     subplot(2,1,1)
    plot(jd(cutoff1:end-cutoff2)- plotstart,P(cutoff1:end-cutoff2)) % to cut off the deployment and recovery
    xlabel('days'), ylabel('pressure (dbar)')
    title(['Seagauage s/n: ' num2str(serialnumber)...
        '; target depth: ' num2str(instrdepth) ' (m)'])
    [p2]=subplot(2,1,2);hold on;grid on;
%     subplot(2,1,2)
    tdum = jd(cutoff1:end-cutoff2)-plotstart;
    dum = auto_filt(P(cutoff1:end-cutoff2),1,1/192);
    tgood = find(tdum>tdum(1)+1 & tdum<tdum(end)-1); % to cut off edge effects of filtering
    plot(tdum(tgood),dum(tgood)); % to cut off the deployment and recovery
    xlabel('days'), ylabel('pressure (dbar)')
    title(['Seagauage s/n: ' num2str(serialnumber)...
        '; target depth: ' num2str(instrdepth) ' (m)', '  48 hour filtered'])
    linkaxes([p1,p2],'x');grid on;
    print(1,'-depsc',[outfile '.eps'])
    
    
    % --------- make logfile entries ----------------
    
    sz = size(P);
    fprintf(log,'Median Pressure [dbar]: %5.1f\n',median(P));
    fprintf(log,'Median Temperature [deg C]: %5.1f\n',median(T));
    fprintf(log,'Start date and time: %s \n',datestr(gregorian(jd(1))));
    fprintf(log,'End date and time:   %s \n',datestr(gregorian(jd(end))));
    sampling_rate = round(1./median(diff(jd)));
    ex_samples = round((jd(end)-jd(1))*sampling_rate+1);
    fprintf(log,'Sampling Frequency [per day]: %d \n',sampling_rate);
    fprintf(log,'Number of samples: %d; expected: %d \n\n\n',sz(1),ex_samples);
    if toffset ~= 0
        fprintf(log,'Offset of %8.4f days has been subtracted from recored time \n',toffset);
        fprintf(1,'Offset of %8.4f days has been subtracted from recored time \n',toffset);
    end
    if jd(end) < bottomstop
        fprintf(log,['\n\n W A R N I N G: Record already ends before end',...
            'of mooring deployment period: \n Recorded time could be wrong!! \n']);
    end
    if jd(1) > bottomstart
        fprintf(log,['\n\n W A R N I N G: Record only starts after beginning',...
            'of mooring deployment period: \n Recorded time could be wrong!! \n']);
    end
    
    % ------save data (in rodb) ---------
    
    
    out = save_seagauge(outfile,P,T,C,S,jd,moor,lat,lon,wd,sdate,stime,edate,etime,instrdepth,serialnumber);
    
    
    
end

fclose(log);

