function [hydrodir,grdatdir,boundarydir,fmoor,cm_check_plot,data_version,...
            outputfile,outputfile_stacked,...
            stddy_tol,std_win,nloop,graphics,...
            JG,pgg,idepth] = setup(lastyear, moor, basedir)
  
    % in- and output directories
    hydrodir = [basedir '/osnap/data/moor/proc/velocity_grid/'];
    grdatdir = [basedir '/osnap/data/moor/proc/velocity_grid_merged/'];
    boundarydir = [basedir '/exec/gitrepo/stage3/gridding/CM/DAT/'];
    
    % turns on/off check plots. off=false, on=true
    cm_check_plot = false ;  
    
    % add start and end of total time period
    jg_start                = datenum(2014,07,01,00,00,00);
    jg_end                  = datenum(lastyear,07,15,00,00,00);
    
    jg_start_str = datestr(jg_start,'YYYYmm');
    jg_end_str = datestr(jg_end,'YYYYmm');
    
    % put out data version?
    data_version = 'v1'; 
    
    JG = jg_start: 0.5: jg_end; % full time series using 2 samples per day
    pgg = 0:20:2000; % depths in 20dbar bins
    idepth = 40; % depth of shallowest instrument, steps of 20 (i.e. if shallowest
                 % instrument is at 50m, select 40m

    switch moor
        case 'RTWB1'
            fmoor = {'CM_rtwb1_osnap_01_2014',...
                    'CM_rtwb1_osnap_02_2015',...
                    'CM_rtwb1_osnap_03_2016',...
                    'CM_rtwb1_osnap_04_2017',...
                    'CM_rtwb1_osnap_05_2018',...
                    'CM_rtwb1_osnap_06_2020',...
                    'CM_rtwb1_osnap_07_2022'};
            % output filenames (should be automatic)
            outputfile = [moor '_merg_linear_interp_' jg_start_str '_' jg_end_str];
            outputfile_stacked = ['CM_rtwb1_stacked_' jg_start_str '_' jg_end_str,...
                                    '_' data_version];
        case 'RTEB1'
             fmoor = {'CM_rteb1_osnap_01_2014',...
                    'CM_rteb1_osnap_02_2015',...
                    'CM_rteb1_osnap_03_2016',...
                    'CM_rteb1_osnap_04_2017',...
                    'CM_rteb1_osnap_05_2018',...
                    'CM_rteb1_osnap_06_2020',...
                    'CM_rteb1_osnap_07_2022'};
            % output filenames (should be automatic)
            outputfile = [moor '_merg_linear_interp_' jg_start_str '_' jg_end_str];
            outputfile_stacked = ['CM_rteb1_stacked_' jg_start_str '_' jg_end_str,...
                                    '_' data_version];
         case 'RTWB2'
             fmoor = {'CM_rtwb2_osnap_01_2014',...
                    'CM_rtwb2_osnap_02_2015',...
                    'CM_rtwb2_osnap_03_2016',...
                    'CM_rtwb2_osnap_04_2017',...
                    'CM_rtwb2_osnap_05_2018',...
                    'CM_rtwb2_osnap_06_2020',...
                    'CM_rtwb2_osnap_07_2022'};
            % output filenames (should be automatic)
            outputfile = [moor '_merg_linear_interp_' jg_start_str '_' jg_end_str];
            outputfile_stacked = ['CM_rtwb2_stacked_' jg_start_str '_' jg_end_str,...
                                    '_' data_version];
    end
    
    % Praemble for 4.b despike time series
    stddy_tol  = 10; % tolerance range of differences between adjacent values
    std_win    = 3.5; % 3.5 * std of the time series (median pm std_wind*std)
    nloop    = 5; % max number of despiking repetitions
    graphics   = 'y'; %y if plots of despiking on, 'n' if off
end