% S4 data conversion routine!
%function s42rodb_v5(infile,outfile,infofile,log,channels,SRBchannels);
% INPUTS:- infile - s4 ascci data file
%          outfile - output rodb file
%          infofile - mooring info file
%          log - filename of log file
% Uses the following functions:-
% hms2h.m
% month_convert.m
% rodbload.m
% rodbsave.m

% Files used:- depth_linearization_coefficients.txt - file containing all
% coefficients for all instruments for correction of pressure record. (file
% saved in stage1 directory - will need to be updated if calibration changes.

% This routine should hopefully be able to deal with any ascii format that the S4 outputs
% starting with the .S4A extension and including whether or not it has Special Record Blocks
% and whatever analogue channels are recorded at each sample.
% Due to the problems with converting .S4B files using the S4 processing software it was decided
% that it would be best to download in ascii format (hex values) and use Matlab to do the conversions.
%
% The download process has been modified further to use a program written
% in visual basic to download the S4 and convert the data to a more useable
% format. Using VB to do the conversion is a lot faster than Matlab so a
% call the the s42rodb_quick function has been included in this rouinte to
% run with the alternative data format.

% Written by Darren Rayner
% Written to only work with serial numbers that start with 35 as this covers the ones we have
% in the Rapid 26.5N mooring array.

% CHANGES:-
    % 11/01/2006 - fixed bug with SRB_interval. previous version never
    % followed "No SRB" route in code. DR.
    % 12/01/2006 - fixed bug with using continuous operation (e.g. CTD
    % calibration dips). Previous version could not handle on time being
    % "00 FF 00". DR.
    % 12/01/2006 - fixed bug with channels not being calculated correctly
    % when using less than 5. DR.
    % 19/01/2006 - changed assignment of time stamps in non-SRB route to
    % include when have averaging. Previously assumed if have no SRBs, have
    % no avargaing. Not the case.
    % 11/9/2006 - included conversion for data format that is produced from
    % Darren's S4download VB routine.
    % 6/12/2006 - fixed bug with selecting which route to follow for which
    % data format.
    % 6/12/2006 - Fixed bug with Heading not being calculated correctly.
    % 15/12/2006 - corrected calculation of pressure. Now reads depth 
    % linearization coefficients from seperate file to correct pressure.
    % 15/12/2006 - produce v5 to incorporate all changes above.
    % 11/07/2007 - fixed bug where heading was not correct if 90 deg.
    %              previously would give heading as -90 deg.
    % 02/11/2007 - fixed naming convention for files generated by DR's
    %              download routines to be .asc instead of .cap. DR.
    % 2010/12/28 - created a script to run the s42rodb_v5 function, in the
    % similar format as the microcat scripts
    
clear all
close all
% startup
m_setup
basedir = '/noc/users/pstar/rpdmoc/rapid/data/';
cruise='jc103';
operator='bim';
moor = 'mar3_9_201240';

infofile=[basedir,'moor/proc/',moor,'/',moor,'info.dat'];
inpath = [basedir,'moor/raw/',cruise,'/s4/'];
outpath = [basedir,'moor/proc/',moor,'/s4/'];
channels = [2 3 4 5 6];
SRBchannels = [2 3 4 5 6];

s4_id = 302;
[id,sn,z,s_t,s_d,e_t,e_d,lat,lon,wd,mr]=...
    rodbload(infofile,['instrument:serialnumber:z:Start_Time:Start_Date:'...
                    'End_Time:End_Date:Latitude:Longitude:WaterDepth:Mooring']);

ii = find(id==s4_id);
sn = sn(ii);
z = z(ii);
id = id(ii);

[z,zx]=sort(z);
sn = sn(zx);
id = id(zx);

for proc = 1:length(sn)
    disp(num2str(sn(proc)))
    infile = [inpath,num2str(sn(proc)),'_data.asc'];
    outfile = [outpath,moor,'_',num2str(sn(proc)),'.raw'];
    log = [inpath,num2str(sn(proc)),'_data.cap'];
    s42rodb_v5(infile,outfile,infofile,log,channels,SRBchannels);
end

% function s42rodb_v5(infile,outfile,infofile,log,channels,SRBchannels);
% if nargin==5
%  % does nothing
% elseif nargin==4
%  % does nothing
% elseif nargin==6
%  % does nothing
% else
%     infile = input('Please enter name and full path of input S4 ascii file:','s')
%     outfile= input('Please enter name and full path of output rodb file:','s')
%     infofile= input('Please enter name and full path of mooring info file:','s')
%     log= input('Please enter name and full path of log file:','s')
% end

