
global MEXEC.SITE MEXEC.VERSION_FILE MEXEC.HISTORY_DIRECTORY MEXEC.Mhousekeeping_version
global MEXEC.PLATFORM_TYPE MEXEC.PLATFORM_IDENTIFIER MEXEC.PLATFORM_NUMBER
global MEXEC.MSTAR_TIME_ORIGIN MEXEC.COMMENT_DELIMITER_STRING
global MEXEC.MUSER
global MEXEC.Mcarter
global MEXEC.MEXEC_DATA_ROOT MEXEC.MEXEC_CWD MEXEC.MDIRLIST
global MEXEC.PEXEC_DATA_ROOT MEXEC.PEXEC_CWD MEXEC.PDIRLIST
global MEXEC.Mrsh_machine MEXEC.Mrsh_dataroot_local MEXEC.Mrsh_dataroot_remote
global MEXEC.MSCRIPT_CRUISE_STRING MEXEC.Mtechsas_root MEXEC.Mtechsas_torg MEXEC.Mtechsas_default_navstream
global MEXEC.MDEFAULT_DATA_TIME_ORIGIN
global MEXEC.Muse_version_lockfile
global MEXEC.Mshipdatasystem
global MEXEC.Mscs_root MEXEC.Mscs_mat MEXEC.Mscs_sed MEXEC.Mscs_torg MEXEC.Mscs_default_navstream
global MEXEC.Mship